HTML5 mac and linux instructions corrections
use "terminal" for mac and linux consistency (instead of copy pasta
error: of using "command prompt" which is nomrally used for DOS)